name = "tax-plus-v1"
client_id = "3bd4f52fbfebb0cc1fbdecbac33dc580"
application_url = "https://tax-plus-v1-production.up.railway.app"
embedded = true

[access_scopes]
scopes = "read_products,write_products,read_cart_transforms,write_cart_transforms"

[auth]
redirect_urls = [
  "https://tax-plus-v1-production.up.railway.app/auth/callback",
  "https://tax-plus-v1-production.up.railway.app/auth/shopify/callback",
  "https://tax-plus-v1-production.up.railway.app/api/auth/callback"
]

[webhooks]
api_version = "2026-04"

[pos]
embedded = false
