api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "japan-import-tax"
type = "function"
uid = "452a4951-e568-66d5-a43e-4ee3231f9c5ed98a2143"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
